app:
  message: Message sent to the RabbitMQ queue Successfully
server:
  port: 9090
#Specify rabbitMQ configuration
spring:
  rabbitmq: 
    host: localhost
    password: guest
    port: 15672
    username: guest
    exchange: employee.exchange
    queue: employee.queue
    routingkey: employee.routingkey

